[package]
name = "hodges"
version = "0.1.0"
authors = ["Adam Harries <harries.adam@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.4"
flame = "0.2.2"
flamer = "0.3"
rand = "0.6.5"

[build-dependencies]
bindgen = "0.47.1"
cmake = "0.1.35"
