[package]
name = "hodges"
version = "0.1.0"
authors = ["Adam Harries <adam.harries@codeplay.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.4"
flame = "0.2.2"
flamer = "0.3"

[build-dependencies]
bindgen = "0.37.0"
cmake = "0.1.31"
