# Audio sources.
# All audio from archive.org

DL=wget -O $@

all: things.mp3 squatty.mp3 rabbits.mp3 campus.mp3 bess.mp3 rent.mp3 stars.mp3 blues.mp3

things.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestraThingsAintWhatTheyUsedToBe1941/Johnny_Hodges_Orchestra-Things_Aint_What_They_Used_To_Be-1941.mp3

squatty.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestraSquatyRoo1941/Johnny_Hodges_Orchestra-Squaty_Roo-1941.mp3

rabbits.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestra-TheRabbitsJump/Johnny_Hodges_Orchestra-The_Rabbits_Jump-1939.mp3

campus.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestra-SwinginOnTheCampus/Johnny_Hodges_Orchestra-Swingin_On_The_Campus-1939.mp3

bess.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestra-GoodQueenBess/Johnny_Hodges_Orchestra-Good_Queen_Bess-1940.mp3

rent.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestraRentPartyBlues1939/Johnny_Hodges_Orchestra-Rent_Party_Blues-1939.mp3

stars.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestra-DancingOnTheStars/Johnny_Hodges_Orchestra-Dancing_On_The_Stars-1938.mp3

blues.mp3:
	$(DL) https://archive.org/download/JohnnyHodgesOrchestra-ThatsTheBluesOldMan/Johnny_Hodges_Orchestra-Thats_The_Blues_Old_Man-1940.mp3

clean:
	rm *.mp3